spring.application.name=Superfume

# Conexión a Supabase 

spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.mseuhoqwkeqlniuyfpsr
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración del pool de conexiones Hikari para Supabase
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Desactivar Flyway por ahora
spring.flyway.enabled=false

# Configuración del servidor
server.port=8080
server.servlet.context-path=/api

# CORS - Permitir requests desde React
spring.web.cors.allowed-origins=http://localhost:5173,http://localhost:5175,https://xmvxyz.github.io,http://44.218.26.62,http://44.218.26.62:80,http://44.218.26.62:8080
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true



